name: Wow Packager
on:
    workflow_dispatch:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+(-(ALPHA|BETA))*"
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Clone project
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Package and Publish
              uses: BigWigsMods/packager@v2
